# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170703_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.CharField(default='hap', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.CharField(default='post/post/2018/03/07/default.mp4', max_length=100),
        ),
    ]
